#!/bin/bash -e

# This is the OpenResty setup
set -eo pipefail

# Needed for ldconfig
export PATH=$PATH:/sbin

version=${OPENRESTY_VERSION:-1.7.2.1}
install_dir="$OPENSHIFT_HOMEDIR/usr/$version"
build_dir="$OPENSHIFT_HOMEDIR/build"
src_dir="$build_dir/src"
log_dir="$build_dir/logs"
log_file="$log_dir/lapis_build"
MAKE_JOBS=$(grep processor /proc/cpuinfo  | wc -l)

pcre_ver=${PCRE_VERSION:-8.33}
pcre_file=${PCRE_FILE:-pcre-$pcre_ver.tar.gz}
pcre_url=${PCRE_URL:-http://sourceforge.net/projects/pcre/files/pcre/$pcre_ver/$pcre_file}

openresty_ver=${OPENRESTY_VERSION:-1.7.2.1}
openresty_file=${OPNERESTY_FILE:-ngx_openresty-$openresty_ver.tar.gz}
openresty_url=${OPENRESTY_URL:-http://openresty.org/download/$openresty_file}

luarocks_ver=${LUAROCKS_VERSION:-2.1.2}
luarocks_file=${LUAROCKS_FILE:-luarocks-$luarocks_ver.tar.gz}
luarocks_url=${LUAROCKS_URL:-http://luarocks.org/releases/$luarocks_file}

# Luarocks installs these
moonscript_ver=${MOONSCRIPT_VERSION:-0.2.6}
lapis_ver=${LAPIS_VERSION:-1.0.4}

export LUA_PATH="$install_dir/share/lua/5.1/?.lua;$install_dir/lualib/?.lua;;"
export LUA_CPATH="$install_dir/lualib/?.so;;"

# Needed so we don't need the full path after installing
export PATH=$install_dir/bin:$PATH

build_PCRE()
{
	# no build step
	return
}

build_OpenResty()
{
	echo "       Building OpenResty" | tee -a $log_file
	cd $src_dir/OpenResty-$openresty_ver/ngx_openresty-$openresty_ver/
	./configure --prefix=$install_dir --with-pcre=$src_dir/PCRE-$pcre_ver/pcre-$pcre_ver/ --with-http_ssl_module | tee -a $log_file
	make -j${MAKE_JOBS:-2} | tee -a $log_file
	make install | tee -a $log_file
	# Should fix issue #1 with LuaRocks not finding luajit's headers
	ln -s $install_dir/luajit/include/luajit-*/* $install_dir/luajit/include/
	make clean
}

build_LuaRocks()
{
	echo "       Building LuaRocks" | tee -a $log_file
	cd $src_dir/LuaRocks-$luarocks_ver/luarocks-$luarocks_ver/
	./configure --prefix=$install_dir --with-lua=$install_dir/luajit | tee -a $log_file
	make | tee -a $log_file
	make install | tee -a $log_file
	return
}

# Arguments:
# Name
# Version
# url
# filename
get_ver()
{
	if test -d $src_dir/$1-$2
	then
		echo "-----> Using $1 $2" | tee -a $log_file
	else
		mkdir -p $src_dir/$1-$2
		cd $src_dir/$1-$2
		echo "       First download, may take several minutes" | tee -a $log_file
		echo "-----> Installing $1 $2..." | tee -a $log_file
		curl -sOL $3
		tar zxf $4
		rm -f $4
		build_$1
		echo " done" | tee -a $log_file
	fi
}

mkdir -p $build_dir $src_dir $log_dir
get_ver "PCRE" "$pcre_ver" "$pcre_url" "$pcre_file"
get_ver "OpenResty" "$openresty_ver" "$openresty_url" "$openresty_file"
get_ver "LuaRocks" "$luarocks_ver" "$luarocks_url" "$luarocks_file"

luarocks install moonscript $MOONSCRIPT_VERSION | tee -a $log_file
luarocks install lapis $LAPIS_VERSION | tee -a $log_file

