#!/bin/bash
# Utility functions for use in the cartridge scripts.

function parse_args {
    while :
    do
        case $1 in
            -h | --help | -\?)
                echo "usage: $0 [--version[=]<value>]"
                exit 0
                ;;
            -v | --version)
                version=$2     # You might want to check if you really got VERSION
                shift 2
                ;;
            --version=*)
                version=${1#*=}        # Delete everything up till "="
                shift
                ;;
            --) # End of all options
                shift
                break
                ;;
            -*)
                echo "WARN: Unknown option... Exiting: $1" >&2
                exit 1
                ;;
            *)  # no more options. Stop while loop
                break
                ;;
        esac
    done
}

function luarocks_config {
	install_dir="$1"

	cat > $install_dir/etc/luarocks/config-5.1.lua << EOCFG
rocks_trees = {
   { name = [[system]], root = [[$install_dir]] }
}

local_cache = [[$install_dir/.cache]]
EOCFG
}
